const kioskbody = [
  "<span id='impact'> Inspired by authentication kiosks at the front of the school,</span> this display and its card-swiping sidekick form a connected security system for the school's machine room.",
].join('\n');
const signbody = [
  "NULL"
].join('<br>');
const kioskv2body = [
  "<span id='impact'><a href='https://www.youtube.com/watch?v=d00b5Rq0R1A&t'>video out on youtube!<a> <br>A second iteration </span>to the machine room kiosk at Millburn High School's robotics lab. This new system tackles the design issues of its predecessor, designed with special care for a lab that shaped high school for me.","","<b>Stability:</b>","- Dedicated voltage regulation circuitry helps keep a stable power supply. (5.02V, 10A max)","- A fan pointed directly at the processor drastically reduces internal temperatures.","- Intake and outtake vents guide air through the display, expelling hot air from the top.","- Hardware drivers now run from startup and constantly monitor the fan and card swiper, regardless of network connection.","","<b>Build upgrades:</b>","- The casing of this kiosk is now over 40% smaller through the use of a laser cut body and tight tolerances around the bezel.","- Probably my favorite part, the brushed gold aluminum trim is able to stay almost completely flush with the body of the kiosk! I did this with a custom bending tool.", "- Rigidity is a very important aspect of kiosk design. The more something flexes when you tap it, the less comfortable it is to use. Using standoffs as internal reinforcements, it's far more rigid allowing for more precise touch input."
].join('<br>');
const lightingbody = [
  "<span id='impact'></span> This client's unique needs - to highlight trees, a patio, and a general walkway at independent hours, raised the need for a connected installation that they could easily control from their fingertips. This led me to a shocking realization: <b>Smart landscape lighting isn't smart yet.</b> Mainstream landscape lighting manufacturers only provide dated setups that either rely on RF remotes, switching entirely separate transformers on and off, or the classic \"All-in-one\" smart platform. <br><img src=\"https://imgs.xkcd.com/comics/standards.png\" style=\"border-radius:0.5em\"> <br> To avoid the expensive, bulky, overcomplex, or inconvenient setup for this client's simple need to turn the lights on and off, I designed an outdoor control box to complete the installation.<br><img src=\"./relaybox_far-1.webp\"./relaybox_far.jpeg\" style=\"border-radius:0.5em\"><br> <b>This sealed box sits is the connecting piece between the transformer indoors, and the lights outdoors.</b> Alongside serving as a junction box for wires, it connects the common returns for each zone through a smart relay (ZooZ MultiRelay). The smart relay communicates wirelessly with a Raspberry Pi running Home Assistant, an open-source home automation platform. This system allows for each zone to be controlled off of completely independent schedules depending on outdoor conditions.<br><br><i>Note: Huge thanks to the client who took these photos post-installation! </i>"
].join('<br>');
const robotbody = [
  "<span id='impact'><a href='https://www.youtube.com/watch?v=XHtXNaQUAIE'>reveal video on youtube</a><br>8405 mk2.2</span>, the final bot a bunch of nerds and I worked on for the 2022-2023 FTC Season. Ending off my four years of high school robotics, this bot was meant to be small, lightweight, and nimble, which was pulled off via the use of over 82 custom parts and months of CAD. We made it to states with only one returning member this year, and I think that's pretty remarkable. I can't wait to see what the students at the MILL pull off next. Thanks for a great four years <3."
].join('<br>');
const cesiumbody = ['NULL'];
//"","<b>Software and Drivers:</b>","- Hardware drivers now run from startup and constantly monitor the fan, temperatures, and card swiper, regardless of its server connection.", "- The card swiper drivers now allow the machine room to be unlocked wirelessly by any teacher on the network."